CREATE TABLE "Processados" (
	"id"	INTEGER,
	"sentenca"	TEXT,
	"mod_ren"	TEXT,
	"entity1"	TEXT NOT NULL,
	"entity2"	TEXT NOT NULL,
	"entity_type1"	TEXT NOT NULL,
	"entity_type2"	TEXT NOT NULL,
	"referencia"	TEXT,
	"id_corpus"	INTEGER,
	"id_extracao"	INTEGER,
	"limpeza"	TEXT,
	"mod_er"	TEXT,
	"relation1"	TEXT,
	"score1"	TEXT,
	"relation2"	TEXT,
	"score2"	TEXT,
	"relation3"	TEXT,
	"score3"	TEXT,
	"proc"	TEXT,
	"perc_treino"	TEXT,
	"cod_relacao"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);